[project]
name = "travelagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "airportsdata>=20241001",
    "googletrans==4.0.0rc1",
    "pyairports>=2.1.1",
    "python-dotenv>=1.0.1",
    "transliterate>=1.10.2",
]
