"""empty message

Revision ID: 3910ba82df8e
Revises: 764f3629caac
Create Date: 2024-03-24 22:49:05.715263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3910ba82df8e'
down_revision: Union[str, None] = '764f3629caac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations', sa.Column('place', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'lon')
    op.drop_column('locations', 'lat')
    op.drop_column('locations', 'place')
    op.drop_table('travel_notes')
    op.drop_table('travel_members')
    # ### end Alembic commands ###
