"""empty message

Revision ID: 764f3629caac
Revises: 7fccee90688e
Create Date: 2024-03-21 16:16:39.732163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764f3629caac'
down_revision: Union[str, None] = '7fccee90688e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('user', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['user'], ['id'])
    op.add_column('travels', sa.Column('user', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'travels', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travels', type_='foreignkey')
    op.drop_column('travels', 'user')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'user')
    # ### end Alembic commands ###
