"""empty message

Revision ID: 7fccee90688e
Revises: cbcce179a2d3
Create Date: 2024-03-21 16:03:43.052353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fccee90688e'
down_revision: Union[str, None] = 'cbcce179a2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('travel', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'travels', ['travel'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'travel')
    # ### end Alembic commands ###
