"""add fields to travel note model

Revision ID: ed925f3428d4
Revises: d37557da5b01
Create Date: 2024-03-25 17:03:08.143793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed925f3428d4'
down_revision: Union[str, None] = 'd37557da5b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_notes', sa.Column('note_type', sa.String(), server_default='text', nullable=True))
    op.add_column('travel_notes', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_notes', 'file_url')
    op.drop_column('travel_notes', 'note_type')
    # ### end Alembic commands ###
